#pragma once

enum Errno {
  ERR_NOT_PERMITTED = -1,
  ERR_NOT_FOUND = -2,
  ERR_NO_MEMORY = -4,
  ERR_IO = -5,
  ERR_BAD_FILE = -9,
  ERR_PERMISSION_DENIED = -13,
  ERR_ALREADY_EXISTS = -17,
  ERR_NOT_A_DIRECTORY = -20,
  ERR_IS_A_DIRECTORY = -21,
  ERR_INVALID_ARGUMENT = -22,
  ERR_NO_SPACE = -28,
  ERR_DIRECTORY_NOT_EMPTY = -39,
};
