#pragma once

#define FILECTRL_READONLY 0x001
#define FILECTRL_WRITEONLY 0x002
#define FILECTRL_READWRITE (FILECTRL_READONLY | FILECTRL_WRITEONLY)
#define FILECTRL_CREATE 0x004
#define FILECTRL_TRUNCATE 0x008
#define FILECTRL_APPEND 0x010
