#pragma once

enum Syscall {
  SYSCALL_UNKNOWN = 0,
  SYSCALL_PUTCHAR,
  SYSCALL_GETCHAR,
  SYSCALL_EXIT,
  SYSCALL_OPEN,
  SYSCALL_READ,
  SYSCALL_WRITE,
  SYSCALL_CLOSE,
  SYSCALL_GET_FILE_NAME,
  SYSCALL_GET_FILE_SIZE,
  SYSCALL_SPAWN,
  SYSCALL_WAIT,
  SYSCALL_YIELD,
  SYSCALL_KMESG,
  SYSCALL_STAT,
  SYSCALL_CHDIR,
  SYSCALL_GETCWD,
  SYSCALL_MKDIR,
  SYSCALL_RM,
  SYSCALL_SBRK,
};
